@HostAddress = http://localhost:5188

GET {{HostAddress}}/api/Account
Accept: application/json
Authorization: Bearer hi

###

POST {{HostAddress}}/api/Account/Login
Accept: text/plain
Content-Type: application/json

{
    "accountId": 1,
    "email": "fake@mail.com",
    "username": "foobar",
    "password": "hihi"
}

###

POST {{HostAddress}}/api/Account/Refresh
Accept: text/plain
Content-Type: application/json

{
    "token": "",
    "accountId": 1
}

###

DELETE {{HostAddress}}/api/Account/1

###

GET {{HostAddress}}/api/Review?ForGame=1

###

GET {{HostAddress}}/api/Game/1

###

GET {{HostAddress}}/api/Game

###

DELETE {{HostAddress}}/api/Review/Likes/2/1

###

GET {{HostAddress}}/api/Review/Likes/2

###

GET {{HostAddress}}/api/Account/1

###

PUT {{HostAddress}}/api/Account/1/Follow/2

###

PUT {{HostAddress}}/api/Account/2/Follow/1
